version=1.0.1
group=princ.animatedloadingoverlay
java_version=21

minecraft_version=1.21.11
mod_name=Animated Loading Overlay
mod_author=PrincParshia
mod_id=animated_loading_overlay
license=All Rights Reserved
credits=
description=The Loading Animation Minecraft Actually Deserves!
minecraft_version_range=[1.21.11, 1.22)
neo_form_version=1.21.11-20251209.172050
parchment_minecraft=1.21.11
parchment_version=2025.12.20

fabric_version=0.141.5+1.21.11
fabric_loader_version=0.19.2

neoforge_version=21.11.44
neoforge_loader_version_range=[4,)

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
